import WagmiProvider from '@/context/WagmiContext';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import AppProvider from '@/context/AppProvider';
import SetupWeb3Modal from './SetupWeb3Modal';
import { ReactNode } from 'react';
import AuthContext from '@/context/AuthContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'EventCrib | First Web3 Event Management System',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  auth,
}: {
  children: React.ReactNode;
  auth: ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className} id='main_layout'>
        <AuthContext>
          <WagmiProvider>
            <Toaster position='bottom-right' />
            <AppProvider>
              {children}
              {auth}
            </AppProvider>
          </WagmiProvider>
        </AuthContext>
        <SetupWeb3Modal />
      </body>
    </html>
  );
}
